import type { IssuesState } from '../data/useIssues';
import type { Changelog as Changes, IssueRecord } from '../types';
const sets = (c?: Changes) => ({'help topics':c?.docsToc ?? [],'available actions':c?.paidActions ?? [],'help pages':c?.docsRoutes ?? [],'work instructions':(c?.skills ?? []).map(s=>`${s.id}@${s.version}`),'network features':c?.versionFeatures ?? [],'running services':(c?.services ?? []).map(s=>`${s.kind} ${s.version} ${s.up}`),'worker software':c?.workerRelease?.tag ? [c.workerRelease.tag] : [],'network software':c?.versionCommit ? [c.versionCommit] : []});
function differences(older: IssueRecord,newer:IssueRecord){const a=sets(older.data.changelog),b=sets(newer.data.changelog);return Object.keys(b).flatMap(k=>{const key=k as keyof typeof b,added=b[key].filter(x=>!a[key].includes(x)),removed=a[key].filter(x=>!b[key].includes(x));return added.length||removed.length ? [{key,added,removed}]:[];});}
export function Changelog({state}:{state:IssuesState}) {
 const asc=[...state.issues].sort((a,b)=>a.date.localeCompare(b.date));
 if(!state.bundledReady)return <p role="status">Opening the change record…</p>;
 return <article className="changelog-page"><p className="small-label page-title">THE NETWORK, DAY BY DAY</p><h1>What changed</h1><p className="standfirst">A comparison of the public records saved with each issue. A changed record tells us what was visible at the time of reading.</p>
 {asc.slice(1).reverse().map(newer=>{const older=asc[asc.indexOf(newer)-1]!;const changes=differences(older,newer);return <section className="change-note" key={newer.date}><p className="small-label">{older.date} → {newer.date}</p><h2>{changes.length ? 'The network’s public records changed' : 'Nothing changed in the recorded protocol lists'}</h2>{changes.length ? <ul>{changes.map(c=><li key={c.key}>{c.key==='work instructions' ? `${c.added.length} work instructions were added or updated; ${c.removed.length} earlier versions left the list.` : c.key==='worker software' ? 'The worker software has a new release.' : c.key==='network software' ? 'The network reports a different software build.' : c.key==='running services' ? 'The software versions or availability of running services changed.' : `${c.added.length} entries were added and ${c.removed.length} removed from the ${c.key}.`}</li>)}</ul>:<p>The saved help topics, actions, work instructions, features, software and services match.</p>}<details><summary>technical details · compare the two records</summary>{changes.map(c=><div key={c.key}><h3>{c.key}</h3><ul>{c.added.map(s=><li className="diff-add" key={'a'+s}>added: <code>{s}</code></li>)}{c.removed.map(s=><li className="diff-del" key={'r'+s}>removed: <code>{s}</code></li>)}</ul></div>)}<p><a href={older.base+'data.json'}>{older.date} source data</a> · <a href={newer.base+'data.json'}>{newer.date} source data</a></p></details></section>;})}
 <h2 className="section-rule">the saved record</h2>{asc.map(r=><details key={r.date}><summary>{r.date} · issue {r.number} · technical details</summary><pre>{JSON.stringify(r.data.changelog,null,2)}</pre></details>)}{asc.length<2 && <p>A comparison will appear when the next issue arrives.</p>}</article>;
}
